"""Device lifecycle wrapper used by the integrated simulation."""

from __future__ import annotations

from dataclasses import dataclass, field

from phase1.device import Device


@dataclass
class DeviceAgent:
    """
    Represents one simulated IIoT device throughout its lifecycle.

    The underlying Phase 1 Device object is created only once.
    The same DID, ECC key pair and Device object are then reused
    throughout Phase 1 and Phase 2.

    The agent also stores simulation information such as arrival
    time, registration state, assigned batch and temporary token.
    """

    device_type: str
    arrival_time: int

    # Whether this device needs to operate before the epoch
    # has been finalized.
    needs_immediate_access: bool = False

    # Actual Phase 1 Device.
    # Created once after the DeviceAgent is initialized.
    device: Device = field(init=False)

    # Lifecycle information.
    state: str = field(
        default="CREATED",
        init=False,
    )

    batch_id: str | None = field(
        default=None,
        init=False,
    )

    leaf_hash: str | None = field(
        default=None,
        init=False,
    )

    epoch_id: int | None = field(
        default=None,
        init=False,
    )

    # Phase 2 temporary credential.
    temporary_token: str | None = field(
        default=None,
        init=False,
    )

    # Permanent proof will be assigned after batch finalization.
    permanent_proof: object | None = field(
        default=None,
        init=False,
    )

    def __post_init__(self) -> None:
        """
        Create the actual Phase 1 Device exactly once.

        Device() generates the DID and ECC key pair.
        """

        if self.arrival_time < 0:
            raise ValueError(
                "device arrival time cannot be negative"
            )

        self.device = Device(
            self.device_type
        )

    # =========================================================
    # DEVICE IDENTITY
    # =========================================================

    @property
    def did(self) -> str:
        """Return the DID generated by the Phase 1 Device."""

        return self.device.did

    @property
    def private_key(self):
        """
        Return the device private key.

        Used by the simulator when the device must sign
        challenges or Phase 2 request nonces.
        """

        return self.device.private_key

    @property
    def public_key_bytes(self) -> bytes:
        """Return the Phase 1 device public key."""

        return self.device.public_key_bytes

    # =========================================================
    # PHASE 1 REGISTRATION
    # =========================================================

    def register(self, fog_node):
        """
        Perform Phase 1 registration using the existing Device.

        This calls the original Phase 1 registration workflow:

        PSK authentication
        challenge generation
        ECC proof of possession
        DID and public key submission
        leaf creation
        batch insertion
        """

        if self.state != "CREATED":
            raise RuntimeError(
                f"device {self.did} cannot register "
                f"from state {self.state}"
            )

        result = self.device.register(
            fog_node,
            fog_node.psk,
        )

        self.batch_id = result.batch_id
        self.leaf_hash = result.leaf_hash
        self.state = "QUEUED"

        return result

    # =========================================================
    # PHASE 2
    # =========================================================

    def assign_temporary_token(
        self,
        token: str,
    ) -> None:
        """
        Store the temporary Phase 2 credential.

        Token generation itself remains the responsibility of
        TokenService.
        """

        if self.state != "QUEUED":
            raise RuntimeError(
                f"temporary token cannot be assigned "
                f"while device is in state {self.state}"
            )

        self.temporary_token = token
        self.state = "PROVISIONAL"

    # =========================================================
    # FINALIZATION
    # =========================================================

    def mark_permanent(
        self,
        epoch_id: int,
        proof,
    ) -> None:
        """
        Mark the same device as permanently registered after
        its batch has been finalized and its Merkle inclusion
        proof has been obtained.
        """

        if self.state not in {
            "QUEUED",
            "PROVISIONAL",
        }:
            raise RuntimeError(
                f"device {self.did} cannot become permanent "
                f"from state {self.state}"
            )

        self.epoch_id = epoch_id
        self.permanent_proof = proof

        # Temporary bridging is no longer needed.
        self.temporary_token = None

        self.state = "PERMANENT"

    # =========================================================
    # STATUS HELPERS
    # =========================================================

    @property
    def is_waiting_for_inclusion(self) -> bool:
        """Return True while permanent Merkle inclusion is pending."""

        return self.state in {
            "QUEUED",
            "PROVISIONAL",
        }

    @property
    def has_temporary_access(self) -> bool:
        """Return whether the device currently has a temporary token."""

        return (
            self.state == "PROVISIONAL"
            and self.temporary_token is not None
        )

    @property
    def has_permanent_identity(self) -> bool:
        """Return whether permanent Merkle membership exists."""

        return (
            self.state == "PERMANENT"
            and self.epoch_id is not None
            and self.permanent_proof is not None
        )

    # =========================================================
    # DISPLAY
    # =========================================================

    def display_arrival(self) -> None:
        """Print device arrival information."""

        print("\n--- Device Arrival ---")

        print(
            f"\n[DEVICE_ARRIVAL] "
            f"time={self.arrival_time}s "
            f"did={self.did} "
            f"type={self.device_type}"
        )

    def display_status(self) -> None:
        """Print the current lifecycle state."""

        print(
            f"[DEVICE_STATE] "
            f"did={self.did} "
            f"state={self.state} "
            f"batch={self.batch_id} "
            f"epoch={self.epoch_id}"
        )